## FIXME : Customize project constants for your application.

## Swagger Information's
swagger.app-info.name=Library Manager
swagger.app-info.description=Spring Boot Project
swagger.app-info.version=1.0.0
swagger.contact.name=Isaac de Sousa
swagger.contact.url=https://github.com/Isaac-Sousa/
swagger.contact.email=isaacsousadev@gmail.com